[nfs]
172.31.23.112 ansible_ssh_user='ec2-user'

[webservers]
172.31.21.49 ansible_ssh_user='ec2-user' 
172.31.27.134 ansible_ssh_user='ec2-user'

[db]
172.31.21.20 ansible_ssh_user='ec2-user' 

[lb]
172.31.9.142 ansible_ssh_user='ubuntu'